INSERT INTO MOVIE(id, title, actor, genre, year, rating) VALUES (1, 'The Shawshank Redemption', 'Morgan Freeman', 'DRAMA', 1994, 9.3);
INSERT INTO MOVIE(id, title, actor, genre, year, rating) VALUES (2, 'The Dark Knight', 'Christian Bale', 'ACTION', 2008, 9.0);
INSERT INTO MOVIE(id, title, actor, genre, year, rating) VALUES (3, 'Inception', 'Leonardo DiCaprio', 'SCIFI', 2010, 8.8);
INSERT INTO MOVIE(id, title, actor, genre, year, rating) VALUES (4, 'The Conjuring', 'Patrick Wilson', 'HORROR', 2013, 7.5);
INSERT INTO MOVIE(id, title, actor, genre, year, rating) VALUES (5, 'The Suicide Squad', 'Margot Robbie', 'COMEDY', 2021, 7.6);
INSERT INTO MOVIE(id, title, actor, genre, year, rating) VALUES (6, 'Edge of Tomorrow', 'Tom Cruise', 'SCIFI', 2014, 7.9);
INSERT INTO MOVIE(id, title, actor, genre, year, rating) VALUES (7, 'Taken', 'Liam Neeson', 'DRAMA', 2008, 7.9);
INSERT INTO MOVIE(id, title, actor, genre, year, rating) VALUES (8, 'Fight Club', 'Brad Pitt', 'DRAMA', 1999, 8.8);
INSERT INTO MOVIE(id, title, actor, genre, year, rating) VALUES (9, 'Jungle Cruise', 'Dwayne Johnson', 'COMEDY', 2021, 6.7);
INSERT INTO MOVIE(id, title, actor, genre, year, rating) VALUES (10, 'It (I)', 'Jaedon Martell', 'HORROR', 2017, 7.3);
INSERT INTO MOVIE(id, title, actor, genre, year, rating) VALUES (11, 'The Departed', 'Leonardo DiCaprio', 'DRAMA', 2006, 8.5);
INSERT INTO MOVIE(id, title, actor, genre, year, rating) VALUES (12, 'Iron Man', 'Robert Downey Jr.', 'ACTION', 2008, 8.5);
INSERT INTO MOVIE(id, title, actor, genre, year, rating) VALUES (13, 'Star Wars: Episode VII - The Force Awakens', 'Daisy Ridley', 'SCIFI', 2015, 7.8);
INSERT INTO MOVIE(id, title, actor, genre, year, rating) VALUES (14, 'Apocalypto', 'Gerardo Taracena', 'DRAMA', 2006, 7.8);
INSERT INTO MOVIE(id, title, actor, genre, year, rating) VALUES (15, 'Baywatch', 'Dwayne Johnson', 'COMEDY', 2017, 5.5);
INSERT INTO MOVIE(id, title, actor, genre, year, rating) VALUES (16, 'The Fast and the Furious: Tokyo Drift', 'Lucas Black', 'ACTION', 2006, 6.0);
INSERT INTO MOVIE(id, title, actor, genre, year, rating) VALUES (17, '3 Ninjas: High Noon at Mega Mountain', 'Hulk Hogan', 'COMEDY', 1998, 3.0);
INSERT INTO MOVIE(id, title, actor, genre, year, rating) VALUES (18, 'Harry Potter and the Deathly Hallows: Part 2', 'Daniel Radcliffe', 'DRAMA', 2011, 8.1);
INSERT INTO MOVIE(id, title, actor, genre, year, rating) VALUES (19, 'The Forever Purge', 'Ana de la Reguera', 'HORROR', 2021, 5.4);
INSERT INTO MOVIE(id, title, actor, genre, year, rating) VALUES (20, 'Scream', 'Neve Campbell', 'HORROR', 1996, 7.3);